const Constants = {
    NAME_MIN_LENGTH: 5,
    NAME_MAX_LENGTH: 255,
    EMAIL_MIN_LENGTH: 5,
    EMAIL_MAX_LENGTH: 255,
    USERNAME_MIN_LENGTH: 5,
    USERNAME_MAX_LENGTH: 255,
    PASSWORD_MIN_LENGTH: 5,
    PASSWORD_MAX_LENGTH: 1024,
    COURSECODE_LENGTH: 6,
    COURSE_MIN_LENGTH: 10,
    COURSE_MAX_LENGTH: 255,
}

module.exports = Constants;